// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using baiquanlyweb.Context;

namespace baiquanlyweb.Migrations
{
    [DbContext(typeof(quanlydbcontext))]
    partial class quanlydbcontextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("baiquanlyweb.Models.quanly", b =>
                {
                    b.Property<int>("masp")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(6)
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<float>("giaban")
                        .HasColumnType("real");

                    b.Property<DateTime>("hansudung")
                        .HasColumnType("datetime2");

                    b.Property<string>("nhasx")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tensp")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("masp");

                    b.ToTable("quanlies");
                });
#pragma warning restore 612, 618
        }
    }
}
